/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2015-12-14 17:37:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("  <title>主页</title>\r\n");
      out.write("  <!-- <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> -->\r\n");
      out.write("  <link href=\"pages/css/top_style.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"pages/js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("     function changeButtonStatusMouseOver(){\r\n");
      out.write("         $(\".topButton\").css(\"color\",\"#FFFFFF\");\r\n");
      out.write("         $(\".topButton\").css(\"background-color\",\"#FF9900\");\r\n");
      out.write("\t }\r\n");
      out.write("     function changeButtonStatusMouseOut(){\r\n");
      out.write("\t\t $(\".topButton\").css(\"color\",\"#FF9900\");\r\n");
      out.write("         $(\".topButton\").css(\"background-color\",\"\");\r\n");
      out.write("\t }\r\n");
      out.write("  </script>\r\n");
      out.write("  <div class=\"floatInfo\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"top\">\r\n");
      out.write("    <div class=\"blackPurdah\"></div>\t   \r\n");
      out.write("\t<div class=\"name\">\r\n");
      out.write("\t       <strong>QuickPay&ATM</strong>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"topButton\" align=\"center\" onclick=\"window.location.href='http://139.129.24.81:8082/QuickATM/pfs?pagePath=login.jsp'\" onmouseout=\"changeButtonStatusMouseOut()\" onmousemove=\"changeButtonStatusMouseOver()\">\r\n");
      out.write("\t  <span class=\"buttonText\">\r\n");
      out.write("\t      <strong>点击进入</strong>\t  \r\n");
      out.write("\t  </span>\r\n");
      out.write("\t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"intro3\">\r\n");
      out.write("    <div>\r\n");
      out.write("       <img src=\"pages/image/Snip20151215_1.png\" style=\"width:50%;height:83%\"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("       <label class=\"introText\">\r\n");
      out.write("\t     <strong>快捷支付体验</strong>\r\n");
      out.write("\t   </label>\r\n");
      out.write("\t </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"intro1\">\r\n");
      out.write("     <label class=\"introText\" style=\"left:10%;\">\r\n");
      out.write("\t    <strong>安全支付保障</strong>\r\n");
      out.write("\t </label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("     <img src=\"pages/image/Snip20151215_2.png\" style=\"width:50%;height:83%\"/>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"intro2\">\r\n");
      out.write("     <label class=\"introText\">\r\n");
      out.write("\t    <strong>方便支付需求</strong>\r\n");
      out.write("\t </label>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"pageInfo\">\r\n");
      out.write("     <div class=\"introText\" style=\"position:relative;left:50%;top:30%\">\r\n");
      out.write("\t  \t<a href=\"http://www.baidu.com\">\r\n");
      out.write("\t\t    <strong>联系我们</strong>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t </div>\r\n");
      out.write("     <div class=\"introText\" style=\"position: relative;\r\n");
      out.write("left:42%;\">\r\n");
      out.write("\t  \t<strong>备案信息:XXXXXXXXXXXXX</strong>  \r\n");
      out.write("\t </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
